name: CI
on:
  push:
    branches:
      - master
      - develop*
  pull_request:
    branches:
      - master
      - develop*
jobs:
  test:
    runs-on: [ubuntu-22.04, macos-12, windows-2022]
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ 3.8, 3.9, "3.10" ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          cache: 'pip'
          cache-dependency-path: setup.cfg
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .
          pip install ".[lint, test]"

      - name: Run tests
        run: pytest -v -n auto
